### ISSUE TITLE
connect subjects to Termennetwerk

### ISSUE THREAD

**Issue by liekeverhelst** [netwerk-digitaal-erfgoed/project-organisations-datasets#9]
In the data are references to skos:Concepts via schema.org/subject. These skos:Concepts should preferably come from Termennetwerk

**Comment by sdevalk** [comment]
My suggestion would be to drop `schema:subject` and related properties for now. The NDE ontology doesn't support these: subjects often are literals rather than URIs and subjects frequently do not say much about the actual contents of a dataset (e.g. because it's difficult to use terms that describe all resources in a set accurately).

**Comment by roland-c** [comment]
Those subjects are from CKAN registries. I will remove those for now. 

Also, my bad, but schema:subject doesn't exist, it is schema:about and the inverse property is schema:subjectOf ....

**Comment by roland-c** [comment]
For now, the subjects are dismissed... 
But we should reconsider this because it is mentioned for many datasets and in an ontology like DCAT it is elaborated even much further!
